### ISSUE TITLE
Feature: Chocobo skills/experience data

### ISSUE THREAD

**Issue by alydevs** [PrincessRTFM/WoLua#2]
Perhaps on Game.Player.Buddy, passing through FFXIVClientStructs.FFXIV.Client.Game.UI.Buddy?

**Comment by VariableVixen** [comment]
Unfortunately, I don't have the money to renew my subscription, which is lapsing in two days, so I won't be able to test this feature until I can get it back. Once I do though, I'll look into this!

**Comment by alydevs** [comment]
After some poking I added

```csharp
	private unsafe FFXIVClientStructs.FFXIV.Client.Game.UI.Buddy buddyState = UIState.Instance()->Buddy;
	public uint? BuddyXP => this.Loaded ? this.buddyState.CurrentXP : 0;
```

at https://github.com/PrincessRTFM/WoLua/blob/master/WoLua/Lua/Api/Game/PlayerApi.cs#L43, this worked to show current xp as needed. Dalamud is lacking proper safe access to Buddy classes at the moment and the data on those structs is annoying to try to access. Thanks for replying, hope you can find funds for the game soon.

**Comment by VariableVixen** [comment]
A friend was able to send me enough, so I'm good now. I'll take a look at adding this and doing some testing. That particular addition feels iffy because you're caching the instance for the whole runtime of the plugin, but I can definitely fiddle it around a little to make sure it's safe, and I can probably add other field access too.

**Comment by PrincessRTFM** [comment]
Had my numbers wrong. Subscription fell through. Keeping this open because I should be able to get it back next month, and I can at least try to work on the source in the meantime even if I can't test it yet.

**Comment by VariableVixen** [comment]
Yeah, talking with some other devs reveals that `UIState.Instance()->Buddy` apparently returns `IntPtr.Zero` when the chocobo isn't present, which means that this might not be doable in a good way... still looking into it, though.

**Comment by VariableVixen** [comment]
Okay, a different dev says it's _always_ accessible, even if it's not unlocked. Gonna have to poke around, but I don't think I can test with it not being unlocked, since I don't have such a character.

**Comment by VariableVixen** [comment]
It's not on the player api, you'll need to use `Game.Chocobo` to access the fields, but it's already documented in `docs/chocobo.md`

**Comment by alydevs** [comment]
Thank you so much!
